services:
  gluetun: # Allows qBittorrent Web UI to run through a VPN
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PROTONVPN_PRIVATE_KEY}
      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=${PROTONVPN_SERVER_COUNTRIES}
    env_file:
      - ../.env
    ports:
      - 8080:8080 # qBittorrent Web UI
      - 8001:8000 # Gluetun Control Server (Mapped to 8001 to avoid Seafile conflict)
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${STORAGE_PATH}/appdata/qbittorrent:/config
      - ${STORAGE_PATH}/media:/data/media
    depends_on:
      - gluetun
    restart: unless-stopped

  qbittorrent-port-updater:
    image: alpine:latest
    container_name: qbittorrent-port-updater
    network_mode: service:gluetun
    environment:
      - QBIT_USER=${QBITTORRENT_USERNAME}
      - QBIT_PASS=${QBITTORRENT_PASSWORD}
    volumes:
      - ./port-updater.sh:/usr/local/bin/port-updater.sh
    command: sh -c "apk add --no-cache curl && /usr/local/bin/port-updater.sh"
    depends_on:
      - gluetun
      - qbittorrent
    restart: unless-stopped

# To check what port has been forwarded: --------------------------------------
# docker logs gluetun 2>&1 | grep "port forwarded"
