include:
  - home-assistant/compose.yaml
  - pihole/compose.yaml
  - seafile/compose.yaml
  - homepage/compose.yaml
  - portainer/compose.yaml
  - socket-proxy/compose.yaml
  - qbittorrent/compose.yaml
  - servarr/compose.yaml
  - jellyfin/compose.yaml
  - whatsupdocker/compose.yaml
