include:
  - home-assistant/compose.yaml
  - pihole/compose.yaml
  - seafile/compose.yaml
  - homepage/compose.yaml
  - portainer/compose.yaml
  - downloads/compose.yaml
  - servarr/compose.yaml
  - jellyfin/compose.yaml
