services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code_server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - PASSWORD=${CODE_SERVER_PASSWORD}
    env_file:
      - ../.env
    volumes:
      - /mnt/external/appdata/homeassistant:/config
    ports:
      - 8443:8443
    restart: unless-stopped
