services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${STORAGE_PATH}/appdata/home-assistant:/config
      - ${STORAGE_PATH}:/mnt/external:ro
      - /:/host_fs:ro
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    privileged: true

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ${STORAGE_PATH}/appdata/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true
    restart: always
