services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/external/appdata/home-assistant:/config
      - /mnt/external:/mnt/external:ro
      - /:/host_fs:ro
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    network_mode: host
    privileged: true

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 800M
    volumes:
      - /mnt/external/appdata/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    privileged: true
    restart: always
