services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - ../.env
    volumes:
      - ./homepage:/app/config
      - ./homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_VAR_HOST_IP=${HOST_IP}
      - HOMEPAGE_ALLOWED_HOSTS=${HOST_IP}:3000,${TAILSCALE_IP}:3000
      - HOMEPAGE_VAR_PIHOLE_PASSWORD=${PIHOLE_PASSWORD}
      - HOMEPAGE_VAR_QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
      - HOMEPAGE_VAR_QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
      - HOMEPAGE_VAR_RADARR_API_KEY=${RADARR_API_KEY}
      - HOMEPAGE_VAR_PROWLARR_API_KEY=${PROWLARR_API_KEY}
      - HOMEPAGE_VAR_PORTAINER_ACCESS_KEY=${PORTAINER_ACCESS_KEY}
      - HOMEPAGE_VAR_JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
